### ISSUE TITLE
TypeError: Cannot read property 'port' of null

### ISSUE THREAD

**Issue by zszszsz** [newrelic/node-mitm-server#3]
server.port = server.address().port
at MITMServer.initServer (node_modules\mitm-server\index.js:61:33)
    at MITMServer.listen (node_modules\mitm-server\index.js:29:8)

**Comment by zszszsz** [comment]
it goes like this

```
//proxy.js
var proxy_servers=[];
for(var l of config.listen){
        console.log(JSON.stringify(l));
        //{"address":"::0","port":8887}
        proxy_servers.push(
            (new mitm(options,handler)).listen(l.port,l.address));
    }
```

**Comment by zszszsz** [comment]
it seems running after I comment the 
`server.port = server.address().port`
but I cannot understand this error, in other cases server.address() returns currently

**Comment by zszszsz** [comment]
and I understand it require openssl but npm cannot do it

**Comment by hayes** [comment]
There are some hosts for which spinning up a server seems to currently fail.  In these cases we were not correctly handling the error (We were missing a return statement).  As of 1.4.2 this will still log an error, but no longer crash the process

**Comment by hayes** [comment]
Sorry this took so long to get fixed, I accidentally had notifications for this repo disabled

**Comment by hayes** [comment]
Since this specific error is fixed, I've opened up a new issue that I believe better describes the underlying cause #5
